version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "INSTALL DEPENDENCIES"
      - npm ci

  pre_build:
    commands:
      - npm test

  build:
    commands:
      - npm run build

reports:
  junit-reports:
    files:
      - "reports/unit-reports/junit/*.xml"
    file-format: "JUNITXML"
